app/views/user.py
import os
from flask import Blueprint, render_template, url_for, request, flash, get_flashed_messages, redirect, current_app
from app.forms import RegisterForm, LoginForm, UploadForm, FindPwdForm, passwordForm, emailForm
from app.models import User
from app.exts import db, photos
from app.email import send_mail
from flask_login import login_required, login_user, logout_user, current_user
from PIL import Image

users = Blueprint('users', __name__)


# 注册
@users.route('/register/', methods=['GET', 'POST'])
def register():
    form = RegisterForm()
    if form.validate_on_submit():
        u = User(username=form.username.data, password=form.password.data, email=form.email.data)
        db.session.add(u)
        db.session.commit()

        # 生成token  用u对象调用模型中的方法
        token = u.generate_active_token()
        send_mail(u.email, '账户激活', 'email/activate', username=u.username, token=token)
        flash("恭喜注册成功,请点击邮件中的链接完成激活")
        return redirect(url_for('users.login'))
    return render_template('user/register.html', form=form)


# 这个方法用来验证token  给用户邮箱发送过去一个完整的url
@users.route('/active/<token>', methods=['GET', 'POST'])
def active(token):
    if User.check_active_token(token):
        flash("账户激活成功")
        return redirect(url_for('users.login'))
    else:
        flash("账户激活失败")
        return redirect(url_for('main.index'))


# 登录
@users.route('/login/', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        u = User.query.filter_by(username=form.username.data).first()
        if not u:
            flash("该用户名不存在")
        elif not u.confirmed:
            flash("该账户没有激活,请激活后登录")
        elif u.verify_password(form.password.data):
            login_user(u, remember=form.remember.data)
            flash("登录成功")
            return redirect(request.args.get('next') or url_for("main.index"))
        else:
            flash("密码不正确")
    return render_template('user/login.html', form=form)


# 退出登录
@users.route('/logout/', methods=['GET', 'POST'])
def logout():
    logout_user()
    flash("退出登录成功")
    return redirect(url_for('main.index'))


@users.route('/test/', methods=['GET', 'POST'])
@login_required
def test():
    return 'this is test'


# 找回密码
@users.route('/find_pwd/', methods=['GET', 'POST'])
def find_pwd():
    form = FindPwdForm()
    if form.validate_on_submit():
        u = User.query.filter_by(username=form.username.data).first()
        if not u:
            flash("该用户名不存在")
        elif not u.email == form.email.data:
            flash("邮箱不正确！！")
        else:
            # 生成token  用u对象调用模型中的方法
            token = u.generate_active_token()
            send_mail(u.email, '密码找回', 'email/findpwd', username=u.username, token=token)
            flash("请点击邮件中的链接找回密码")
            return redirect(url_for('users.find_pwd'))
    return render_template('user/find_pwd.html', form=form)


# 这个方法用来验证token  给用户邮箱发送过去一个完整的url 生成新密码
@users.route('/acfpwd/<username>/<token>', methods=['GET', 'POST'])
def acfpwd(username, token):
    if User.check_active_token(token):
        new_pwd = random_string()
        u = User.query.filter_by(username=username).first()
        u.password = new_pwd
        db.session.commit()
        flash("新密码为：" + new_pwd)
        return redirect(url_for('users.login'))
    else:
        flash("密码找回失败")
        return redirect(url_for('main.index'))


# 修改密码
@users.route('/change_pwd/', methods=['GET', 'POST'])
@login_required
def change_pwd():
    form = passwordForm()
    if form.validate_on_submit():
        if current_user.verify_password(form.oldPassword.data):
            current_user.password = form.newPassword1.data
            # db.session.add(current_user)
            db.session.commit()
            flash('密码修改成功')
            logout_user()
            flash('请重新登录')
            return redirect(url_for("users.login"))
        else:
            flash('密码修改失败')
    return render_template('user/change_pwd.html', form=form)


# 修改邮箱
@users.route('/change_email/', methods=['GET', 'POST'])
@login_required
def change_email():
    form = emailForm()
    if form.validate_on_submit():
        if current_user.email == form.oldEmail.data:
            current_user.email = form.newEmail1.data
            # db.session.add(current_user)
            db.session.commit()
            current_user.confirmed = False
            token = current_user.generate_active_token()
            send_mail(current_user.email, '账户激活', 'email/activate', username=current_user.username, token=token)
            flash("请点击邮件中的链接完成激活")
            return redirect(url_for('users.login'))
    return render_template('user/change_email.html', form=form)


# 修改头像
@users.route('/change_icon/', methods=['GET', 'POST'])
@login_required
def change_icon():
    img_url = ''
    form = UploadForm()
    if form.validate_on_submit():
        # 获取文件后缀
        suffix = os.path.splitext(form.icon.data.filename)[1]
        # 随机文件名  拼接
        filename = random_string() + suffix
        photos.save(form.icon.data, name=filename)
        pathname = os.path.join(current_app.config['UPLOADED_PHOTOS_DEST'], filename)
        img = Image.open(pathname)
        img.thumbnail((128, 128))
        img.save(pathname)
        if current_user.icon != 'default.jpg':
            os.remove(current_app.config['UPLOADED_PHOTOS_DEST'], current_user.icon)
        current_user.icon = filename  # 将新上传的文件名 赋值给 用户的头像
        db.session.add(current_user)  # 保存在数据库中
        flash("头像上传成功")
        return redirect(url_for("users.change_icon"))
    img_url = photos.url(current_user.icon)
    return render_template('user/change_icon.html', form=form, img_url=img_url)


# 生成随机字符串
def random_string(length=16):
    import random
    base_str = '1234567890abcdefhijklmnopqrstuvwxyz'
    return ''.join(random.choice(base_str) for i in range(length))

app/templates/common/base.html
{% extends 'bootstrap/base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}
{#定制标题#}
{% block title %}默认标题{% endblock %}
{#定制导航条#}
{% block navbar %}
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{ url_for('main.index') }}">首页</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="{{ url_for('main.index') }}">博客 <span
                            class="sr-only">(current)</span></a></li>
                    <li><a href="{{ url_for('main.index') }}">新闻</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    {% if current_user.is_authenticated %}
                        <li><a href="{{ url_for('users.logout') }}">退出</a></li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                               aria-haspopup="true"
                               aria-expanded="false">你好,{{ current_user.username }} <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="#">个人中心</a></li>
                                <li><a href="{{ url_for("users.change_pwd") }}">修改密码</a></li>
                                <li><a href="{{ url_for("users.change_email") }}">修改邮箱</a></li>
                                <li role="separator" class="divider"></li>
                                <li><a href="{{ url_for("users.change_icon") }}">修改头像</a></li>
                            </ul>
                        </li>
                    {% else %}
                        <li><a href="{{ url_for("users.login") }}">登录</a></li>
                        <li><a href="{{ url_for("users.register") }}">注册</a></li>
                    {% endif %}
                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>
{% endblock %}

{#定制内容 #}
{% block content %}
    <div class="container">
        {% for message in get_flashed_messages() %}
            <div class="alert alert-warning alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span>
                </button>
                <strong>{{ message }}</strong>
            </div>
        {% endfor %}

        {% block page_content %}
            默认内容
        {% endblock %}
    </div>
{% endblock %}
{#定制脚本#}
{% block scripts %}
    {{ super() }}
    {{ moment.include_moment() }}
    {{ moment.locale('zh-CN') }}
{% endblock %}

app/templates/common/macro.html
{#第一个参数 pagination对象 第二个 跳转到哪里去#}
{% macro pagination_show(pagination,endpoint) %}
<nav aria-label="Page navigation">
  <ul class="pagination">
{#      上一页#}
    <li {% if not pagination.has_prev %} class="disabled" {% else %} {% endif %}>
      <a href="{% if pagination.has_prev %}{{ url_for(endpoint,page=pagination.prev_num,**kwargs) }}{% else %}#{% endif %}" aria-label="Previous">
        <span aria-hidden="true">&laquo;</span>
      </a>
    </li>
{#      中间页码#}
    {% for p in pagination.iter_pages() %}
        {% if p %}
{#            www.baidu.com?page=#}
            <li {% if pagination.page == p  %} class="active" {% endif %}><a href="{{ url_for(endpoint,page=p,**kwargs) }}">{{ p }}</a></li>
        {% else %}
            <li><a href="#">&hellip;</a></li>
        {% endif %}

    {% endfor %}
    



{#      下一页#}
   <li {% if not pagination.has_next %} class="disabled" {% else %}{% endif %}>
      <a href="{% if pagination.has_next %}{{ url_for(endpoint,page=pagination.next_num,**kwargs) }}{% else %}#{% endif %}" aria-label="Previous">
        <span aria-hidden="true">&raquo;</span>
      </a>
    </li>
  </ul>
</nav>

{% endmacro %}